/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    photos: Photo;
    galleries: Gallery;
    testimonials: Testimonial;
    services: Service;
    posts: Post;
    pages: Page;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'hero-slides': HeroSlide;
    'about-page': AboutPage;
    'site-config': SiteConfig;
    'site-design': SiteDesign;
    'booking-settings': BookingSetting;
    availability: Availability;
    'gallery-presets': GalleryPreset;
    'email-templates': EmailTemplate;
  };
  globalsSelect: {
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'site-config': SiteConfigSelect<false> | SiteConfigSelect<true>;
    'site-design': SiteDesignSelect<false> | SiteDesignSelect<true>;
    'booking-settings': BookingSettingsSelect<false> | BookingSettingsSelect<true>;
    availability: AvailabilitySelect<false> | AvailabilitySelect<true>;
    'gallery-presets': GalleryPresetsSelect<false> | GalleryPresetsSelect<true>;
    'email-templates': EmailTemplatesSelect<false> | EmailTemplatesSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin accounts that can log into this dashboard.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Admin: full access, including Users, Site Config, Booking Settings, and Availability. Content Editor: can manage Photos, Galleries, Blog Posts, Testimonials, Services, and Pages, but not those admin-only areas.
   */
  role: 'admin' | 'editor';
  /**
   * When checked, the user is prompted to set a new password before accessing the admin.
   */
  mustChangePassword?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Your photo library. Drop images here and they upload instantly — title and alt text are filled in automatically from the filename so you can bulk-upload without stopping. Edit any photo afterwards to update the details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  /**
   * Auto-filled from the filename on upload. Edit this to give the photo a meaningful name — clients never see it. Example: "Smith Wedding - First Dance".
   */
  title?: string | null;
  /**
   * Describe what is in this photo. Screen readers read this aloud for visually impaired visitors and Google uses it to understand your images. Auto-filled on upload — update it when you have a moment. Example: "Bride and groom laughing during their first dance at an outdoor reception."
   */
  alt?: string | null;
  /**
   * The type of session this photo is from. Used to filter your portfolio.
   */
  category?: ('weddings' | 'portraits' | 'families' | 'couples' | 'brands') | null;
  /**
   * Optional text displayed beneath this photo in galleries. Leave blank for no caption.
   */
  caption?: string | null;
  /**
   * Turn on to feature this photo in the portfolio preview section on your homepage. Up to 6 photos are shown.
   */
  featured?: boolean | null;
  /**
   * Controls the order this photo appears in. Lower numbers appear first. Leave blank and sort manually later.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Curated collections of photos shown on your Portfolio page. Each gallery has a category, a cover photo, and a set of photos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  /**
   * The name of this gallery, shown on your portfolio page. Example: "Smith Wedding" or "Fall Family Portraits".
   */
  title: string;
  /**
   * Auto-generated from the title — you do not need to set this. If you want a custom web address, you can edit it here. Use lowercase letters and hyphens only.
   */
  slug: string;
  /**
   * The type of session this gallery is from. Used to filter your portfolio.
   */
  category: 'weddings' | 'portraits' | 'families' | 'couples' | 'brands';
  /**
   * The photo shown as the preview for this gallery on your portfolio page. Must be a photo already uploaded to All Photos.
   */
  coverPhoto: number | Photo;
  /**
   * Use the button above to add multiple photos at once, or add one at a time with the row picker below. Drag the handle on the left to reorder. The order here is exactly how photos appear on the site.
   */
  photos?:
    | {
        photo: number | Photo;
        id?: string | null;
      }[]
    | null;
  /**
   * Display this gallery with the editorial taped-photo look.
   */
  tapedStyle?: boolean | null;
  /**
   * Turn on to feature this gallery on your homepage.
   */
  featured?: boolean | null;
  /**
   * Controls the order this gallery appears on your portfolio page. Lower numbers appear first. Leave blank and galleries display in the order they were added.
   */
  displayOrder?: number | null;
  isPasswordProtected?: boolean | null;
  password?: string | null;
  allowDownload?: boolean | null;
  /**
   * Draft galleries are hidden from your public portfolio.
   */
  status?: ('published' | 'draft') | null;
  /**
   * Optional full-width hero photo shown at the top of the gallery page.
   */
  heroPhoto?: number | Photo | null;
  clientName?: string | null;
  clientEmail?: string | null;
  expiresAt?: string | null;
  expiryReminderSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Reviews and quotes from your clients, shown on your homepage and testimonials page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The name shown below the quote on your website. Use first names, a couple name like "Sarah & James", or a family name like "The Martinez Family".
   */
  clientName: string;
  /**
   * Paste the client's review exactly as you want it to appear on your website. Keep it genuine — real words from real clients build trust with future bookings.
   */
  quote: string;
  /**
   * The type of session this review is from. Used to give visitors context and helps with SEO. Leave blank if you prefer not to categorise it.
   */
  sessionType?: ('Wedding' | 'Engagement' | 'Portrait' | 'Family' | 'Maternity' | 'Event') | null;
  /**
   * Optional photo to show with this testimonial on the Testimonials page. Pick from your photo library.
   */
  photo?: (number | null) | Photo;
  /**
   * When checked, this testimonial appears in the Testimonials section on your homepage. Uncheck to keep it off the homepage (it will still appear on your full Testimonials page).
   */
  featured?: boolean | null;
  /**
   * Controls the order testimonials appear, both on the homepage and the full Testimonials page. 1 shows first, 2 shows second, and so on. Leave blank and they display in the order they were added.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Your photography services, shown on the Services page. Services with a booking deposit set also appear on the Book a Session page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * The name of this service as it appears on your website, like "Wedding Day" or "Portrait Session".
   */
  title: string;
  /**
   * The category shown above the service name, like "Weddings" or "Portraits".
   */
  eyebrow: string;
  /**
   * A short description of what clients can expect from this session.
   */
  description: string;
  /**
   * Optional details listed under the description, like what is included in the package.
   */
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The price shown on your Services page, like "Starting at $2,500". Leave blank to hide pricing.
   */
  price?: string | null;
  /**
   * The deposit amount clients pay to secure their date, in dollars. For example, enter 500 for a $500 deposit. Leave blank to hide the booking button for this service.
   */
  depositAmount?: number | null;
  /**
   * The position of this service in the list. 1 appears first, 2 appears second, and so on. Leave blank and services display in the order they were added.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Your blog posts, shown on the Blog page and individual post pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The title of your blog post, shown on the blog page and in search results.
   */
  title: string;
  /**
   * Auto-generated from the title — you do not need to set this. Edit here only if you want a custom web address. Use lowercase letters and hyphens only.
   */
  slug: string;
  /**
   * Draft posts are not visible on your website. Set to Published when ready.
   */
  status: 'draft' | 'published';
  /**
   * Defaults to today. You can set a future date to schedule the post — it will appear on your blog on that date.
   */
  publishedAt: string;
  /**
   * The main photo for this post, shown at the top of the post and on the blog listing page.
   */
  coverImage?: (number | null) | Photo;
  /**
   * Used to filter posts on the blog page.
   */
  category?: ('style-guide' | 'portrait-sessions' | 'weddings' | 'behind-the-lens' | 'client-education') | null;
  /**
   * A 1-2 sentence summary shown on the blog listing page. Helps readers decide if they want to read more.
   */
  excerpt?: string | null;
  body?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  published?: boolean | null;
  displayOrder?: number | null;
  showInNav?: boolean | null;
  isHomepage?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Track each client engagement from inquiry through delivery - sessions, payments, and documents all live on the project record.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * A short name for this project. Example: "Smith Wedding" or "Javan Graduation Session".
   */
  title: string;
  /**
   * Where this project is in your pipeline.
   */
  status: 'inquiry' | 'booked' | 'post-production' | 'delivered' | 'archived';
  clientName: string;
  clientEmail: string;
  /**
   * The type of session this project is for.
   */
  projectType?: ('portrait' | 'wedding' | 'family' | 'couples' | 'brand') | null;
  projectDate?: string | null;
  location?: string | null;
  /**
   * Notes about this project. Visible to the client if you choose to share it - not private.
   */
  description?: string | null;
  /**
   * Private notes for you only. Never shown to clients.
   */
  internalNotes?: string | null;
  /**
   * Scheduled or completed sessions for this project.
   */
  sessions?:
    | {
        sessionDate: string;
        location?: string | null;
        sessionType?:
          | ('portrait' | 'engagement' | 'wedding-ceremony' | 'wedding-reception' | 'family' | 'couples' | 'brand')
          | null;
        duration?: number | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Record-keeping only - actual payment processing happens through Stripe on the booking page.
   */
  payments?:
    | {
        label: string;
        amount: number;
        dueDate?: string | null;
        status: 'upcoming' | 'paid' | 'past-due';
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Track contracts and invoices for this project. Store the actual file/signature in DocuSign, Google Drive, or wherever it lives, and link to it here.
   */
  documents?:
    | {
        title: string;
        documentType: 'contract' | 'invoice' | 'model-release' | 'other';
        status: 'draft' | 'sent' | 'signed' | 'void';
        documentDate?: string | null;
        /**
         * For invoices: the invoice total.
         */
        amount?: number | null;
        /**
         * Link to the document in DocuSign, Google Drive, or wherever it lives.
         */
        externalLink?: string | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  category?: T;
  caption?: T;
  featured?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  coverPhoto?: T;
  photos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  featured?: T;
  displayOrder?: T;
  isPasswordProtected?: T;
  password?: T;
  clientName?: T;
  clientEmail?: T;
  expiresAt?: T;
  expiryReminderSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  quote?: T;
  sessionType?: T;
  photo?: T;
  featured?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  eyebrow?: T;
  description?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  price?: T;
  depositAmount?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  coverImage?: T;
  category?: T;
  excerpt?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  published?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  clientName?: T;
  clientEmail?: T;
  projectType?: T;
  projectDate?: T;
  location?: T;
  description?: T;
  internalNotes?: T;
  sessions?:
    | T
    | {
        sessionDate?: T;
        location?: T;
        sessionType?: T;
        duration?: T;
        notes?: T;
        id?: T;
      };
  payments?:
    | T
    | {
        label?: T;
        amount?: T;
        dueDate?: T;
        status?: T;
        notes?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        title?: T;
        documentType?: T;
        status?: T;
        documentDate?: T;
        amount?: T;
        externalLink?: T;
        notes?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The full-screen photo carousel on your homepage. Add, remove, or reorder slides here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  /**
   * Each slide fills the screen on your homepage. Drag the handle to reorder them.
   */
  slides?:
    | {
        /**
         * The photo that fills the screen. Use a high-resolution landscape image for the best result.
         */
        image: number | Photo;
        /**
         * Optional text displayed over the photo. Keep it short — one line works best. Leave blank for a clean photo with no text.
         */
        caption?: string | null;
        /**
         * Controls which slide plays first. 1 plays first, 2 plays second. Leave blank and slides play in the order listed here.
         */
        displayOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for your About page and the about preview section on your homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  /**
   * Your professional photo shown on the About page.
   */
  headshot?: (number | null) | Photo;
  /**
   * A brief description of your photo for screen readers and search engines. Example: "Tynnell Hollins holding a camera outdoors".
   */
  headshotAlt?: string | null;
  /**
   * A short line that captures who you are, shown prominently on your About page. Example: "Photographer & Storyteller".
   */
  tagline?: string | null;
  /**
   * Your full bio shown on the About page. You can use bold, italic, and paragraph breaks.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * A shorter version of your story shown on the homepage. Keep it to 2–3 sentences.
   */
  previewBio?: string | null;
  /**
   * Your core values or philosophy, displayed on your About page.
   */
  values?:
    | {
        /**
         * A short title for this value, like "Authenticity" or "Presence".
         */
        heading: string;
        /**
         * A sentence or two describing what this value means to you.
         */
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global settings for your website — business name, contact info, and social media links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config".
 */
export interface SiteConfig {
  id: number;
  /**
   * Your business name as it appears in browser tabs and search results. Example: "Tynnell Hollins Photography".
   */
  title: string;
  /**
   * Your tagline shown on your homepage. Example: "Capturing life's most meaningful moments".
   */
  tagline?: string | null;
  /**
   * Your contact email address, displayed on your contact page.
   */
  email?: string | null;
  /**
   * Your phone number, displayed on your contact page.
   */
  phone?: string | null;
  /**
   * Your full Instagram URL. Example: https://instagram.com/tynnellhollinsphotography
   */
  instagramUrl?: string | null;
  /**
   * Your full Facebook page URL.
   */
  facebookUrl?: string | null;
  /**
   * Your full TikTok profile URL.
   */
  tiktokUrl?: string | null;
  /**
   * Your full Pinterest profile URL.
   */
  pinterestUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-design".
 */
export interface SiteDesign {
  id: number;
  logoUrl?: string | null;
  faviconUrl?: string | null;
  watermarkEnabled?: boolean | null;
  watermarkUrl?: string | null;
  headingFont?: ('poppins' | 'tangerine' | 'abril') | null;
  bodyFont?: ('poppins' | 'tangerine' | 'abril') | null;
  colorBg?: string | null;
  colorBgAccent?: string | null;
  colorHeading?: string | null;
  colorBody?: string | null;
  colorDetail?: string | null;
  colorBtnBg?: string | null;
  spacingScale?: ('compact' | 'normal' | 'spacious') | null;
  buttonStyle?: ('sharp' | 'rounded' | 'pill') | null;
  animationsEnabled?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls how far in advance clients can request sessions. Changes take effect immediately — no code change needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings".
 */
export interface BookingSetting {
  id: number;
  /**
   * How many hours in advance a client must request a session. Default is 48 hours (2 days). Set to 0 to allow same-day requests.
   */
  minLeadTimeHours: number;
  /**
   * How many months into the future clients can request sessions. Default is 24 months (2 years). Requests beyond this window are rejected.
   */
  maxBookingMonths: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Block out dates when you are unavailable — vacations, personal time, recovery periods. Clients requesting sessions during these windows will see your custom message.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability".
 */
export interface Availability {
  id: number;
  /**
   * Add a range for each period you are unavailable. Clients who try to book during a blocked range will see your message instead.
   */
  blockedRanges?:
    | {
        /**
         * A private note for your reference only — never shown to clients. Example: "Cancun trip" or "Wedding weekend".
         */
        internalLabel: string;
        /**
         * The first day you are unavailable.
         */
        startDate: string;
        /**
         * The last day you are unavailable.
         */
        endDate: string;
        /**
         * Extends the blocked window a few days past your return so you have time to catch up before new sessions begin.
         */
        applyReturnBuffer?: boolean | null;
        /**
         * How many extra days to block after your last unavailable day. Only applies when "Add recovery buffer" is checked.
         */
        returnBufferDays?: number | null;
        /**
         * Shown to clients who try to book during this period. Use {returnDate} as a placeholder for your computed return date. Example: "I'm currently away and will be back accepting inquiries on {returnDate}."
         */
        customerMessage: string;
        notificationSent?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Default values applied automatically whenever a new gallery is created, so you do not have to reconfigure the same options every time. Edited from Settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-presets".
 */
export interface GalleryPreset {
  id: number;
  /**
   * Pre-selected category when creating a new gallery. Leave unset to always require a manual choice.
   */
  defaultCategory?: ('weddings' | 'portraits' | 'families' | 'couples' | 'brands') | null;
  /**
   * Status applied to a gallery when it is first created.
   */
  defaultStatus?: ('published' | 'draft') | null;
  /**
   * New galleries start with the editorial taped-photo look already turned on.
   */
  defaultTapedStyle?: boolean | null;
  /**
   * New galleries start featured on the homepage.
   */
  defaultFeatured?: boolean | null;
  /**
   * New galleries start with client photo downloads turned on.
   */
  defaultAllowDownload?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Copy for the emails sent when you share a gallery with a client, and the automatic reminder sent before it expires. Edited from Settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates".
 */
export interface EmailTemplate {
  id: number;
  shareSubject?: string | null;
  shareHeading?: string | null;
  shareBody?: string | null;
  shareButtonLabel?: string | null;
  reminderSubject?: string | null;
  reminderHeading?: string | null;
  reminderBody?: string | null;
  reminderButtonLabel?: string | null;
  reminderDaysBefore?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        image?: T;
        caption?: T;
        displayOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  headshot?: T;
  headshotAlt?: T;
  tagline?: T;
  bio?: T;
  previewBio?: T;
  values?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-config_select".
 */
export interface SiteConfigSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  email?: T;
  phone?: T;
  instagramUrl?: T;
  facebookUrl?: T;
  tiktokUrl?: T;
  pinterestUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-design_select".
 */
export interface SiteDesignSelect<T extends boolean = true> {
  logoUrl?: T;
  faviconUrl?: T;
  watermarkEnabled?: T;
  watermarkUrl?: T;
  headingFont?: T;
  bodyFont?: T;
  colorBg?: T;
  colorBgAccent?: T;
  colorHeading?: T;
  colorBody?: T;
  colorDetail?: T;
  colorBtnBg?: T;
  spacingScale?: T;
  buttonStyle?: T;
  animationsEnabled?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-settings_select".
 */
export interface BookingSettingsSelect<T extends boolean = true> {
  minLeadTimeHours?: T;
  maxBookingMonths?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-presets_select".
 */
export interface GalleryPresetsSelect<T extends boolean = true> {
  defaultCategory?: T;
  defaultStatus?: T;
  defaultTapedStyle?: T;
  defaultFeatured?: T;
  defaultAllowDownload?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-templates_select".
 */
export interface EmailTemplatesSelect<T extends boolean = true> {
  shareSubject?: T;
  shareHeading?: T;
  shareBody?: T;
  shareButtonLabel?: T;
  reminderSubject?: T;
  reminderHeading?: T;
  reminderBody?: T;
  reminderButtonLabel?: T;
  reminderDaysBefore?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "availability_select".
 */
export interface AvailabilitySelect<T extends boolean = true> {
  blockedRanges?:
    | T
    | {
        internalLabel?: T;
        startDate?: T;
        endDate?: T;
        applyReturnBuffer?: T;
        returnBufferDays?: T;
        customerMessage?: T;
        notificationSent?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}