/**
 * This file is a minimal stub for TypeScript compilation.
 * The full version is auto-generated by Payload via `npx payload generate:types`
 * or during `next build` with the withPayload plugin.
 *
 * Run `npx payload generate:types` to regenerate with full type information.
 */

import type { SerializedEditorState } from '@payloadcms/richtext-lexical'

// Wire our Config into Payload's generic type system so that findGlobal / find
// return properly-typed results without needing explicit cast annotations.
declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}

export interface Photo {
  id: string | number
  title: string
  alt?: string | null
  category?: 'weddings' | 'portraits' | 'families' | 'couples' | 'brands' | null
  caption?: string | null
  featured?: boolean | null
  displayOrder?: number | null
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    } | null
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    } | null
    hero?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    } | null
  } | null
  updatedAt: string
  createdAt: string
}

export interface User {
  id: string | number
  name?: string | null
  email: string
  updatedAt: string
  createdAt: string
}

export interface Gallery {
  id: string | number
  title: string
  slug?: string | null
  category?: string | null
  coverPhoto?: Photo | string | number | null
  photos?: (Photo | string | number)[] | null
  featured?: boolean | null
  displayOrder?: number | null
  updatedAt: string
  createdAt: string
}

export interface Testimonial {
  id: string | number
  clientName: string
  quote: string
  sessionType?: string | null
  displayOrder?: number | null
  updatedAt: string
  createdAt: string
}

export interface Service {
  id: string | number
  title: string
  eyebrow?: string | null
  description?: string | null
  features?: { feature: string; id?: string | null }[] | null
  price?: string | null
  depositAmount?: number | null
  displayOrder?: number | null
  updatedAt: string
  createdAt: string
}

export interface Post {
  id: string | number
  title: string
  slug?: string | null
  status?: 'draft' | 'published' | null
  publishedAt?: string | null
  coverImage?: Photo | string | number | null
  excerpt?: string | null
  body?: SerializedEditorState | null
  updatedAt: string
  createdAt: string
}

export interface HeroSlides {
  slides?:
    | {
        image: Photo | string | number
        caption?: string | null
        displayOrder?: number | null
        id?: string | null
      }[]
    | null
  updatedAt?: string | null
  createdAt?: string | null
  globalType?: string | null
  id: string | number
}

export interface AboutPage {
  headshot?: Photo | string | number | null
  headshotAlt?: string | null
  tagline?: string | null
  bio?: SerializedEditorState | null
  previewBio?: string | null
  values?:
    | {
        heading: string
        body?: string | null
        id?: string | null
      }[]
    | null
  updatedAt?: string | null
  createdAt?: string | null
  globalType?: string | null
  id: string | number
}

export interface SiteConfig {
  title: string
  tagline?: string | null
  email?: string | null
  phone?: string | null
  instagramUrl?: string | null
  facebookUrl?: string | null
  tiktokUrl?: string | null
  pinterestUrl?: string | null
  updatedAt?: string | null
  createdAt?: string | null
  globalType?: string | null
  id: string | number
}

export type Config = {
  collections: {
    photos: Photo
    galleries: Gallery
    testimonials: Testimonial
    services: Service
    posts: Post
    users: User
  }
  globals: {
    'hero-slides': HeroSlides
    'about-page': AboutPage
    'site-config': SiteConfig
  }
}
