/**
 * This file is a minimal stub for TypeScript compilation.
 * The full version is auto-generated by Payload via `npx payload generate:types`
 * or during `next build` with the withPayload plugin.
 *
 * Run `npx payload generate:types` to regenerate with full type information.
 */

export interface Photo {
  id: string | number
  title: string
  alt?: string | null
  category?: 'weddings' | 'portraits' | 'families' | 'couples' | 'brands' | null
  caption?: string | null
  featured?: boolean | null
  displayOrder?: number | null
  url?: string | null
  thumbnailURL?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  sizes?: {
    thumbnail?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    } | null
    card?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    } | null
    hero?: {
      url?: string | null
      width?: number | null
      height?: number | null
      mimeType?: string | null
      filesize?: number | null
      filename?: string | null
    } | null
  } | null
  updatedAt: string
  createdAt: string
}

export interface User {
  id: string | number
  name?: string | null
  email: string
  updatedAt: string
  createdAt: string
}

export interface Gallery {
  id: string | number
  title: string
  slug?: string | null
  category?: string | null
  coverPhoto?: Photo | string | number | null
  photos?: (Photo | string | number)[] | null
  featured?: boolean | null
  displayOrder?: number | null
  updatedAt: string
  createdAt: string
}

export interface Testimonial {
  id: string | number
  clientName: string
  quote: string
  sessionType?: string | null
  displayOrder?: number | null
  updatedAt: string
  createdAt: string
}

export interface Service {
  id: string | number
  title: string
  eyebrow?: string | null
  description?: string | null
  features?: { feature: string; id?: string | null }[] | null
  price?: string | null
  depositAmount?: number | null
  displayOrder?: number | null
  updatedAt: string
  createdAt: string
}

export interface Post {
  id: string | number
  title: string
  slug?: string | null
  status?: 'draft' | 'published' | null
  publishedAt?: string | null
  coverImage?: Photo | string | number | null
  excerpt?: string | null
  body?: Record<string, unknown> | null
  updatedAt: string
  createdAt: string
}

export type Config = {
  collections: {
    photos: Photo
    galleries: Gallery
    testimonials: Testimonial
    services: Service
    posts: Post
    users: User
  }
}
